import s_style_1 from '../Assets/Product/Guitars/S_Style/g1.jpg';
import s_style_2 from '../Assets/Product/Guitars/S_Style/g2.jpg';
import s_style_3 from '../Assets/Product/Guitars/S_Style/g3.jpg';
import s_style_4 from '../Assets/Product/Guitars/S_Style/g4.jpg';
import s_style_5 from '../Assets/Product/Guitars/S_Style/g5.jpg';
import s_style_6 from '../Assets/Product/Guitars/S_Style/g6.jpg';
import s_style_7 from '../Assets/Product/Guitars/S_Style/g7.jpg';
import s_style_8 from '../Assets/Product/Guitars/S_Style/g8.jpg';
import t_style_1 from '../Assets/Product/Guitars/T_Style/g9.jpg';
import t_style_2 from '../Assets/Product/Guitars/T_Style/g10.jpg';
import t_style_3 from '../Assets/Product/Guitars/T_Style/g11.jpg';
import t_style_4 from '../Assets/Product/Guitars/T_Style/g12.jpg';
import t_style_5 from '../Assets/Product/Guitars/T_Style/g13.jpg';
import t_style_6 from '../Assets/Product/Guitars/T_Style/g14.jpg';
import t_style_7 from '../Assets/Product/Guitars/T_Style/g15.jpg';
import t_style_8 from '../Assets/Product/Guitars/T_Style/g16.jpg';
import s_cut_style_1 from '../Assets/Product/Guitars/S_Cut_Style/g17.jpg';
import s_cut_style_2 from '../Assets/Product/Guitars/S_Cut_Style/g18.jpg';
import s_cut_style_3 from '../Assets/Product/Guitars/S_Cut_Style/g19.jpg';
import s_cut_style_4 from '../Assets/Product/Guitars/S_Cut_Style/g20.jpg';
import s_cut_style_5 from '../Assets/Product/Guitars/S_Cut_Style/g21.jpg';
import s_cut_style_6 from '../Assets/Product/Guitars/S_Cut_Style/g22.jpg';
import s_cut_style_7 from '../Assets/Product/Guitars/S_Cut_Style/g23.jpg';
import s_cut_style_8 from '../Assets/Product/Guitars/S_Cut_Style/g24.jpg';
import d_cut_style_1 from '../Assets/Product/Guitars/D_Cut_Style/g25.jpg';
import d_cut_style_2 from '../Assets/Product/Guitars/D_Cut_Style/g26.jpg';
import d_cut_style_3 from '../Assets/Product/Guitars/D_Cut_Style/g27.jpg';
import d_cut_style_4 from '../Assets/Product/Guitars/D_Cut_Style/g28.jpg';
import d_cut_style_5 from '../Assets/Product/Guitars/D_Cut_Style/g29.jpg';
import d_cut_style_6 from '../Assets/Product/Guitars/D_Cut_Style/g30.jpg';
import d_cut_style_7 from '../Assets/Product/Guitars/D_Cut_Style/g31.jpg';
import d_cut_style_8 from '../Assets/Product/Guitars/D_Cut_Style/g32.jpg';
import d_cut_style_9 from '../Assets/Product/Guitars/D_Cut_Style/g33.jpg';
import h_style_1 from '../Assets/Product/Guitars/Heavy/g34.jpg';
import h_style_2 from '../Assets/Product/Guitars/Heavy/g35.jpg';
import h_style_3 from '../Assets/Product/Guitars/Heavy/g36.jpg';
import h_style_4 from '../Assets/Product/Guitars/Heavy/g37.jpg';
import h_style_5 from '../Assets/Product/Guitars/Heavy/g38.jpg';
import h_style_6 from '../Assets/Product/Guitars/Heavy/g39.jpg';


export const data = { 
    guitar:{ 
        S_Style: {
            g_s_1: {
                       id: 1,
                       name: 'Amarok-6 BKNT Flame Burst',
                       pic: s_style_1,
                       info: '',
                       price: 415,
                       brand: 'Harley Benton',
                       first: 'Build: Arched "Modern Comfort',
                       second: 'Body: Mahogany',
                       third: 'Top: Flamed maple veneer',
                       qtn: 12,
                       topSelling: true,
                   },
            g_s_2: {
                        id: 2,
                        name: 'ST-20HSS SBK Standard',
                        pic: s_style_2,
                        info: '',
                        price: 123,
                        brand: 'Harley Benton',
                        first: 'Body: Basswood',
                        second: 'Neck: Maple',
                        third: 'Fretboard: Amaranth',
                        qtn: 23,
                        topSelling: false,
                    },
            g_s_3: {
                        id: 3,
                        name: 'ST-62MN VW Vintage Series',
                        pic: s_style_3,
                        info: '',
                        price: 115,
                        brand: 'Harley Benton',
                        first: 'Vintage Series',
                        second: 'Body: Basswood',
                        third: 'Colour: Vintage White',
                        qtn: 3,
                        topSelling: false,
                    },
            g_s_4: {
                        id: 4,
                        name: 'CST-24T Black Cherry Flame',
                        pic: s_style_4,
                        info: '',
                        price: 225,
                        brand: 'Harley Benton',
                        first: 'Deluxe series',
                        second: 'Body: Mahogany',
                        third: 'Top: Flamed maple',
                        qtn: 1,
                        topSelling: true,
                    },
             g_s_5: {
                        id: 5,
                        name: ' John Petrucci Majesty 6 AC',
                        pic: s_style_5,
                        info: '',
                        price: 5899,
                        brand: 'Music Man',
                        first: 'John Petrucci Signature model',
                        second: 'Body: Mahogany',
                        third: 'Top: FSpalted maple',
                        qtn: 0,
                        topSelling: false,
                     },
             g_s_6: {
                        id: 6,
                        name: 'Player Plus Strat MN OLP',
                        pic: s_style_6,
                        info: '',
                        price: 789,
                        brand: 'Fender',
                        first: 'Colour: Olympic Pearl',
                        second: 'Alder body',
                        third: 'Maple fretboard',
                        qtn: 3,
                        topSelling: false,
                     },
            g_s_7: {
                        id: 7,
                        name: 'Fusion-III HSH Roasted FBB',
                        pic: s_style_7,
                        info: '',
                        price: 333,
                        brand: 'Harley Benton',
                        first: 'Nyatoh body',
                        second: 'Bolt-on neck - maple',
                        third: 'Flamed maple fretboard',
                        qtn: 12,
                        topSelling: false,
                    },
             g_s_28: {
                        id: 8,
                        name: 'John Petrucci Majesty 6 EF',
                        pic: s_style_8,
                        info: '',
                        price: 4499,
                        brand: 'Music Man',
                        first: 'John Petrucci Signature Model',
                        second: 'Body: Mahogany',
                        third: 'Top: Maple',
                        qtn: 0,
                        topSelling: false,
                     },
        },
        T_Style: {
            g_t_1: {
                        id: 9,
                        name: 'TE-90QM Trans Red',
                        pic: t_style_1,
                        info: '',
                        price: 166,
                        brand: 'Harley Benton',
                        first: 'Chambered body: Mahogany',
                        second: 'Top: Flamed maple',
                        third: 'Fretboard: Amaranth',
                        qtn: 7,
                        topSelling: false,
                   },
            g_t_2: {
                        id: 10,
                        name: 'CV 50s Tele MN WHB',
                        pic: t_style_2,
                        info: '',
                        price: 339,
                        brand: 'Squier',
                        first: 'Body: Pine',
                        second: 'Bolt-on neck: Maple',
                        third: 'Fretboard: Maple',
                        qtn: 14,
                        topSelling: true,
                   },
            g_t_3: {
                        id: 11,
                        name: 'Tele 40th Anniv SM',
                        pic: t_style_3,
                        info: '',
                        price: 433,
                        brand: 'Squier',
                        first: '40th Anniversary Vintage',
                        second: 'Maple neck',
                        third: 'Nyatoh body',
                        qtn: 1,
                        topSelling: false,
                    },
            g_t_4: {
                        id: 12,
                        name: 'TE-62CC SP',
                        pic: t_style_4,
                        info: '',
                        price: 124,
                        brand: 'Harley Benton',
                        first: 'Deluxe Series',
                        second: 'Poplar body',
                        third: 'Maple fingerboard',
                        qtn: 9,
                        topSelling: false,
                    },
            g_t_5: {
                        id: 13,
                        name: 'AM Pro II Tele MN 3TSB',
                        pic: t_style_5,
                        info: '',
                        price: 1539,
                        brand: 'Fender',
                        first: 'Body: Alder',
                        second: 'Bolt-on neck: Maple',
                        third: 'Fretboard: Maple',
                        qtn: 2,
                        topSelling: false,
                    },
            g_t_6: {
                        id: 14,
                        name: 'Vintera 60s Tele Modified LPB',
                        pic: t_style_6,
                        info: '',
                        price: 888,
                        brand: 'Fender',
                        first: 'Vintera series',
                        second: 'Bolt-on neck: Maple',
                        third: 'Fretboard: Pau Ferro',
                        qtn: 4,
                        topSelling: true,
                    },
            g_t_7: {
                        id: 15,
                        name: 'JA-90 Jim Adkins NA IL',
                        pic: t_style_7,
                        info: '',
                        price: 822,
                        brand: 'Fender',
                        first: 'Artist series',
                        second: 'Jim Adkins model',
                        third: 'Body: Ash',
                        qtn: 3,
                        topSelling: false,
                    },
            g_t_8: {
                        id: 16,
                        name: 'TE-90FLT Red Blast',
                        pic: t_style_8,
                        info: '',
                        price: 149,
                        brand: 'Harley Benton',
                        first: 'Deluxe Series',
                        second: 'Body: Sungkai',
                        third: 'Bolted neck: Canadian Maple',
                        qtn: 14,
                        topSelling: false,
                    },
            
        },
        S_Cut: {
            g_sc_1: {
                        id: 17,
                        name: 'Les Paul Standard 50s HCS',
                        pic: s_cut_style_1,
                        info: '',
                        price: 1919,
                        brand: 'Gibson',
                        first: 'Body: Mahogany',
                        second: 'Cream-colored body binding',
                        third: 'Top: Maple',
                        qtn: 1,
                        topSelling: false,
                    },
            g_sc_2: {
                        id: 18,
                        name: 'SC-550 II PAF',
                        pic: s_cut_style_2,
                        info: '',
                        price: 249,
                        brand: 'Harley Benton',
                        first: 'Deluxe Series',
                        second: 'Chambered mahogany body',
                        third: 'Curved AAA maple top',
                        qtn: 8,
                        topSelling: false,
                    },
            g_sc_3: {
                        id: 19,
                        name: 'SC-500 BK Vintage Series',
                        pic: s_cut_style_3,
                        info: '',
                        price: 149,
                        brand: 'Harley Benton',
                        first: 'Vintage Series',
                        second: 'Body: Basswood',
                        third: 'Arched top',
                        qtn: 6,
                        topSelling: false,
                    },
            g_sc_4: {
                        id: 20,
                        name: 'SC-450 P90 GT Classic',
                        pic: s_cut_style_4,
                        info: '',
                        price: 124,
                        brand: 'Harley Benton',
                        first: 'Classic Series',
                        second: 'Body: Basswood',
                        third: 'Arched top',
                        qtn: 6,
                        topSelling: false,
                    },
            g_sc_5: {
                        id: 21,
                        name: 'SC-500 WH Vintage Series',
                        pic: s_cut_style_5,
                        info: '',
                        price: 141,
                        brand: 'Harley Benton',
                        first: 'Vintage Series',
                        second: 'Body: Basswood',
                        third: 'Arched top',
                        qtn: 12,
                        topSelling: false,
                    },
            g_sc_6: {
                        id: 22,
                        name: 'Les Paul Standard 60s UB',
                        pic: s_cut_style_6,
                        info: '',
                        price: 1919,
                        brand: 'Gibson',
                        first: 'Body: Mahogany',
                        second: 'Cream-coloured body binding',
                        third: 'Top: AA flamed maple',
                        qtn: 0,
                        topSelling: true,
                    },
            g_sc_7: {
                        id: 23,
                        name: 'Les Paul Tribute SHB',
                        pic: s_cut_style_7,
                        info: '',
                        price: 888,
                        brand: 'Gibson ',
                        first: 'Body: Mahogany ',
                        second: 'weight-reduced body',
                        third: 'Top: Maple',
                        qtn: 1,
                        topSelling: false,
                    },
            g_sc_8: {
                        id: 24,
                        name: 'Les Paul Custom Koa',
                        pic: s_cut_style_8,
                        info: '',
                        price: 533,
                        brand: 'Epiphone',
                        first: 'Mahogany body',
                        second: 'Grained koa top',
                        third: 'Mahogany neck',
                        qtn: 6,
                        topSelling: false,
                    },   
        },
        D_Cut: {
            g_dc_1: {
                        id: 25,
                        name: 'DC-Custom Blue',
                        pic: d_cut_style_1,
                        info: '',
                        price: 207,
                        brand: 'Harley Benton',
                        first: 'Custom Line series',
                        second: 'Body: Mahogany',
                        third: 'Mahogany neck',
                        qtn: 2,
                        topSelling: false,
                    },
            g_dc_2: {
                        id: 26,
                        name: 'DC-580 CH Vintage Series',
                        pic: d_cut_style_2,
                        info: '',
                        price: 115,
                        brand: 'Harley Benton',
                        first: 'Vintage Series',
                        second: 'Body: Basswood',
                        third: 'Set-in neck: Canadian maple',
                        qtn: 15,
                        topSelling: true,
                    },
            g_dc_3: {
                        id: 27,
                        name: 'DC-600 VI Vintage Series',
                        pic: d_cut_style_3,
                        info: '',
                        price: 174,
                        brand: 'Harley Benton',
                        first: 'Body: Mahogany',
                        second: 'Neck: Mahogany',
                        third: 'Neck attachment: Set-in',
                        qtn: 6,
                        topSelling: false,
                    },
            g_dc_4: {
                        id: 28,
                        name: 'SG Classic Worn P-90 Cherry',
                        pic: d_cut_style_4,
                        info: '',
                        price: 315,
                        brand: 'Epiphone',
                        first: 'Body: Mahogany',
                        second: 'Neck: Mahogany',
                        third: 'Fretboard: Indian Laure',
                        qtn: 8,
                        topSelling: true,
                    },
            g_dc_5: {
                        id: 29,
                        name: 'SG ´61 Standard VC',
                        pic: d_cut_style_5,
                        info: '',
                        price: 1389,
                        brand: 'Gibson',
                        first: 'Mahogany body',
                        second: 'Neck: Mahogany',
                        third: 'Fretboard: Rosewood',
                        qtn: 3,
                        topSelling: false,
                    },
            g_dc_6: {
                        id: 30,
                        name: 'DC-Junior FAT Benton Blue',
                        pic: d_cut_style_6,
                        info: '',
                        price: 157,
                        brand: 'Harley Benton',
                        first: 'Mahogany body',
                        second: 'Set-in neck: Mahogany',
                        third: 'Fretboard: Macassar ebony',
                        qtn: 12,
                        topSelling: false,
                    },
            g_dc_7: {
                        id: 31,
                        name: 'SG Classic Worn P-90',
                        pic: d_cut_style_7,
                        info: '',
                        price: 315,
                        brand: 'Epiphone',
                        first: 'Mahogany body',
                        second: 'Neck: Mahogany',
                        third: 'Fretboard: Indian Laurel',
                        qtn: 12,
                        topSelling: false,
                    },
            g_dc_8: {
                        id: 32,
                        name: 'SG Standard ´64 Maestro CH ULA',
                        pic: d_cut_style_8,
                        info: '',
                        price: 3899,
                        brand: 'Gibson',
                        first: 'Murphy Lab model',
                        second: 'One piece body: Mahogany',
                        third: 'Mahogany neck',
                        qtn: 0,
                        topSelling: false,
                    },
            g_dc_9: {
                        id: 33,
                        name: 'SE Custom 24/08 VS',
                        pic: d_cut_style_9,
                        info: '',
                        price: 833,
                        brand: 'PRS',
                        first: 'Body: Mahogany',
                        second: 'Top: Flamed maple ',
                        third: 'Fretboard: Rosewood',
                        qtn: 2,
                        topSelling: false,
                    },
        },
        Heavy: {
            g_h_1: {
                        id: 34,
                        name: 'LTD Arrow-1000 CARS',
                        pic: h_style_1,
                        info: '',
                        price: 1039,
                        brand: 'ESP',
                        first: 'Body: Mahogany',
                        second: 'Neck-through-body neck: Maple',
                        third: 'Fingerboard: Ebony',
                        qtn: 0,
                        topSelling: false,
                    },
            g_h_2: {
                        id: 35,
                        name: 'EX-84 Modern WH',
                        pic: h_style_2,
                        info: '',
                        price: 249,
                        brand: 'Harley Benton',
                        first: 'Pro series',
                        second: 'Mahogany body',
                        third: 'Set-in mahogany neck',
                        qtn: 2,
                        topSelling: true,
                    },
            g_h_3: {
                        id: 36,
                        name: 'Prophecy Extura Purple Tiger',
                        pic: h_style_3,
                        info: '',
                        price: 749,
                        brand: 'Epiphone',
                        first: 'Body: Mahogany',
                        second: 'Top: AAA flamed maple veneer',
                        third: 'Neck: Mahogany',
                        qtn: 7,
                        topSelling: false,
                    },
            g_h_4: {
                        id: 37,
                        name: 'JS32 Kelly Snow White',
                        pic: h_style_4,
                        info: '',
                        price: 283,
                        brand: 'Jackson',
                        first: 'Poplar body',
                        second: 'Amaranth fretboard',
                        third: 'Neck profile: Speed neck',
                        qtn: 2,
                        topSelling: true,
                    },
            g_h_5: {
                        id: 38,
                        name: 'Flying V Prophecy Red Tiger',
                        pic: h_style_5,
                        info: '',
                        price: 739,
                        brand: 'Epiphone',
                        first: '1958 Flying V',
                        second: 'Body: Mahogany',
                        third: 'Top: AAA flamed maple veneer',
                        qtn: 0,
                        topSelling: false,
                    },
            g_h_6: {
                        id: 39,
                        name: 'E-II Horizon-III FM RDB',
                        pic: h_style_6,
                        info: '',
                        price: 1666,
                        brand: 'ESP',
                        first: 'Body: Alder',
                        second: 'Top: Flamed maple',
                        third: 'Neck-thru-body: Maple',
                        qtn: 1,
                        topSelling: false,
                    },
        },
    }
  }